# Generated by Django 5.1.7 on 2025-04-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_english', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialquestion',
            name='question',
            field=models.TextField(verbose_name='Сұрақ мәтіні'),
        ),
    ]
