# Generated by Django 5.1.7 on 2025-03-25 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_english', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Тіркелген қолданушы'),
        ),
        migrations.AddField(
            model_name='module',
            name='user_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to='general_english.userprogress', verbose_name='Қолданушы курсы'),
        ),
        migrations.AddField(
            model_name='writing',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing', to='general_english.module', verbose_name='Қай модульге тиесілі'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('course', 'user')},
        ),
    ]
