# Generated by Django 5.1.7 on 2025-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_english', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingquestion',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='readingquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='context',
            field=models.TextField(default='default', help_text='Бұл сұрақ қатысты мәтін үзіндісі', verbose_name='Оқу мәтіні'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Сурет сілтемесі'),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='general_english.module', verbose_name='Қай модульге тиесілі'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='source',
            field=models.TextField(blank=True, null=True, verbose_name='Дереккөз'),
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
