# Generated by Django 5.1.7 on 2025-04-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_english', '0002_alter_trialquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Сұрақ'),
        ),
    ]
