# Generated by Django 5.1.7 on 2025-04-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_english', '0004_alter_modulescore_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='audio_question',
            field=models.TextField(blank=True, null=True, verbose_name='Audio Question'),
        ),
    ]
