# Generated by Django 5.1.7 on 2025-04-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_english', '0007_remove_optionattempt_correct_option_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
