# Generated by Django 5.1.7 on 2025-04-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Атауы')),
            ],
            options={
                'verbose_name_plural': 'Оқу дәрежесі',
            },
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(help_text='Мерзімді санмен енгізіңіз', verbose_name='Мерзімі')),
                ('prefix', models.CharField(help_text='Мысалы: ай, жыл', max_length=100, verbose_name='Бірлік')),
            ],
            options={
                'verbose_name_plural': 'Оқыту ұзақтығы',
            },
        ),
        migrations.CreateModel(
            name='FieldsOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Атауы')),
                ('tuition_fee', models.DecimalField(decimal_places=2, help_text='Оқу құны, мысалы: 150000.00', max_digits=10, verbose_name='Оқу құны')),
            ],
            options={
                'verbose_name_plural': 'Оқу аумағы',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Атауы')),
            ],
            options={
                'verbose_name_plural': 'Оқыту тілі',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Атауы')),
            ],
            options={
                'verbose_name_plural': 'Орналасқан жері',
            },
        ),
        migrations.CreateModel(
            name='StudyFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Атауы')),
            ],
            options={
                'verbose_name_plural': 'Оқыту форматы',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Университет туралы')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/', verbose_name='Логотип')),
                ('key_summary', models.TextField(blank=True, null=True, verbose_name='Қысқаша шолу')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='Кіріспе')),
                ('academic_requirements', models.TextField(blank=True, null=True, verbose_name='Академиялық талаптар')),
                ('scholarships_funding', models.TextField(blank=True, null=True, verbose_name='Стипендия және қаржыландыру')),
                ('degree_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.degreetype', verbose_name='Оқу дәрежесі')),
                ('duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.duration', verbose_name='Оқыту ұзақтығы')),
                ('fields_of_study', models.ManyToManyField(blank=True, to='universities.fieldsofstudy', verbose_name='Оқу аумағы')),
                ('languages', models.ManyToManyField(blank=True, to='universities.language', verbose_name='Оқыту тілдері')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.location', verbose_name='Орналасқан жері')),
                ('study_formats', models.ManyToManyField(blank=True, to='universities.studyformat', verbose_name='Оқыту форматы')),
            ],
            options={
                'verbose_name_plural': 'Университеттер',
            },
        ),
    ]
