# Generated by Django 5.1.7 on 2025-04-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='application_deadline',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='pace',
            field=models.CharField(default='Full Time'),
        ),
        migrations.AddField(
            model_name='university',
            name='tuition_fees',
            field=models.CharField(null=True),
        ),
    ]
