# Generated by Django 5.1.7 on 2025-04-28 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_remove_university_website_university_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='program_benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Неге бұл бағдарламаны таңдау керек?'),
        ),
        migrations.AddField(
            model_name='university',
            name='study_highlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Мұнда оқу нені білдіреді?'),
        ),
    ]
