# Generated by Django 5.1.7 on 2025-05-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_university_program_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='duration',
            field=models.FloatField(help_text='Мерзімді санмен енгізіңіз', verbose_name='Мерзімі'),
        ),
    ]
