# Generated by Django 5.1.7 on 2025-03-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Курс атауы')),
                ('duration', models.PositiveIntegerField(verbose_name='Курс ұзақтығы')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Курс түсініктемесі')),
                ('has_level_define', models.BooleanField(default=False, verbose_name='Деңгей анықтау барма')),
                ('type', models.CharField(choices=[('IELTS', 'IELTS'), ('GENERAL ENGLISH', 'General English')], unique=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курстар',
            },
        ),
    ]
