# Generated by Django 5.1.7 on 2025-03-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('IELTS', 'IELTS'), ('GENERAL ENGLISH', 'General English')], default='GENERAL ENGLISH'),
        ),
    ]
