# Generated by Django 5.1.7 on 2025-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
