# Generated by Django 5.1.7 on 2025-06-18 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0003_chatmessage_attached_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='attached_file',
        ),
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ai_chat.chats')),
            ],
        ),
    ]
