# Generated by Django 5.1.7 on 2025-04-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ieltslistening',
            options={'verbose_name': 'Тыңдалым сұрағы', 'verbose_name_plural': 'Тыңдалым сұрақтары'},
        ),
        migrations.AlterModelOptions(
            name='ieltsmodule',
            options={'verbose_name': 'Бастапқы модуль', 'verbose_name_plural': 'Бастапқы модульдар'},
        ),
        migrations.AlterModelOptions(
            name='ieltssubmodule',
            options={'verbose_name': 'Тармақ', 'verbose_name_plural': 'Тармақтар'},
        ),
        migrations.AlterModelOptions(
            name='ieltstest',
            options={'verbose_name': 'Тармақ тесті', 'verbose_name_plural': 'Тармақ тесттері'},
        ),
        migrations.AlterModelOptions(
            name='ieltswriting',
            options={'verbose_name': 'Жазылым сұрақтары'},
        ),
        migrations.AlterModelOptions(
            name='writingimage',
            options={'verbose_name': 'Жазылым сұрақтар суреті'},
        ),
    ]
