# Generated by Django 5.1.7 on 2025-04-15 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0002_alter_ieltslistening_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ieltslistening',
            options={'verbose_name_plural': 'Listening | Audios'},
        ),
        migrations.AlterModelOptions(
            name='ieltslisteningfillblank',
            options={'verbose_name_plural': 'Listening | Fill-in-the-blanks'},
        ),
        migrations.AlterModelOptions(
            name='ieltslisteningoption',
            options={'verbose_name_plural': 'Listening | Options'},
        ),
        migrations.AlterModelOptions(
            name='ieltslisteningquestion',
            options={'verbose_name_plural': 'Listening | Questions'},
        ),
        migrations.AlterModelOptions(
            name='ieltsmodule',
            options={'verbose_name_plural': 'Admin | IELTS Modules'},
        ),
        migrations.AlterModelOptions(
            name='ieltsreading',
            options={'verbose_name_plural': 'Reading | Passages'},
        ),
        migrations.AlterModelOptions(
            name='ieltsreadingfillblank',
            options={'verbose_name_plural': 'Reading | Fill-in-the-blanks'},
        ),
        migrations.AlterModelOptions(
            name='ieltsreadingoption',
            options={'verbose_name_plural': 'Reading | Options'},
        ),
        migrations.AlterModelOptions(
            name='ieltsreadingquestion',
            options={'verbose_name': 'Оқылым сұрағы', 'verbose_name_plural': 'Оқылым сұрақтары'},
        ),
        migrations.AlterModelOptions(
            name='ieltsreadingselectinsert',
            options={'verbose_name_plural': 'Reading | Select Insert'},
        ),
        migrations.AlterModelOptions(
            name='ieltssubmodule',
            options={'verbose_name_plural': 'Admin | IELTS SubModules'},
        ),
        migrations.AlterModelOptions(
            name='ieltstest',
            options={'verbose_name_plural': 'Admin | IELTS Tests'},
        ),
        migrations.AlterModelOptions(
            name='ieltswriting',
            options={'verbose_name_plural': 'Writing | Tasks'},
        ),
        migrations.AlterModelOptions(
            name='writingimage',
            options={'verbose_name_plural': 'Writing | Images'},
        ),
    ]
