# Generated by Django 5.1.7 on 2025-04-15 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0003_alter_ieltslistening_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ieltsreadingquestion',
            options={'verbose_name': 'Оқылым сұрағы', 'verbose_name_plural': 'Reading | Questions'},
        ),
        migrations.AlterField(
            model_name='ieltslisteningquestion',
            name='question_type',
            field=models.CharField(choices=[('FILL', 'Fill in the Blank'), ('OPTIONS', 'Choice Options')], default='OPTIONS', max_length=32, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='ieltsreadingquestion',
            name='question_type',
            field=models.CharField(choices=[('FILL', 'Fill in the Blank'), ('SELECT_INSERT', 'Select and place in correct order'), ('OPTIONS', 'Choice Options')], default='OPTIONS', max_length=32, verbose_name='Question Type'),
        ),
        migrations.CreateModel(
            name='IeltsTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completion Time')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ielts.ieltstest', verbose_name='IELTS Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'IELTS Test Attempt',
                'verbose_name_plural': 'IELTS Test Attempts',
            },
        ),
        migrations.CreateModel(
            name='IeltsReadingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fill_blank_answer', models.JSONField(blank=True, help_text='Array of candidate answers if the question is fill in the blanks', null=True, verbose_name='Fill-in-the-blanks Answer')),
                ('select_insert_answer', models.JSONField(blank=True, help_text='Candidate selected words or phrases as a JSON array', null=True, verbose_name='Select Insert Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ielts.ieltsreadingquestion', verbose_name='Reading Question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ielts.ieltsreadingoption', verbose_name='Selected Option')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_submissions', to='ielts.ieltstestattempt', verbose_name='Test Attempt')),
            ],
            options={
                'verbose_name': 'IELTS Reading Submission',
                'verbose_name_plural': 'IELTS Reading Submissions',
            },
        ),
        migrations.CreateModel(
            name='IeltsListeningSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fill_blank_answer', models.JSONField(blank=True, help_text='Array of candidate answers if the question is fill in the blanks', null=True, verbose_name='Fill-in-the-blanks Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ielts.ieltslisteningquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ielts.ieltslisteningoption', verbose_name='Selected Option')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_submissions', to='ielts.ieltstestattempt', verbose_name='Test Attempt')),
            ],
            options={
                'verbose_name': 'IELTS Listening Submission',
                'verbose_name_plural': 'IELTS Listening Submissions',
            },
        ),
        migrations.CreateModel(
            name='IeltsWritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField(verbose_name="Candidate's Answer")),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to='ielts.ieltstestattempt', verbose_name='Test Attempt')),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ielts.ieltswriting', verbose_name='Writing Task')),
            ],
            options={
                'verbose_name': 'IELTS Writing Submission',
                'verbose_name_plural': 'IELTS Writing Submissions',
            },
        ),
    ]
