# Generated by Django 5.1.7 on 2025-04-16 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0004_alter_ieltsreadingquestion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ieltsreadingsubmission',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='ieltsreadingsubmission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='ieltsreadingsubmission',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='ieltstestattempt',
            name='test',
        ),
        migrations.RemoveField(
            model_name='ieltstestattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ieltswritingsubmission',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='ieltswritingsubmission',
            name='writing',
        ),
        migrations.CreateModel(
            name='IeltsTestSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('READING', 'Reading'), ('WRITING', 'Writing'), ('LISTENING', 'LISTENING'), ('SPEAKING', 'Speaking')])),
                ('score', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.ieltstest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='IeltsListeningSubmission',
        ),
        migrations.DeleteModel(
            name='IeltsReadingSubmission',
        ),
        migrations.DeleteModel(
            name='IeltsTestAttempt',
        ),
        migrations.DeleteModel(
            name='IeltsWritingSubmission',
        ),
    ]
