# Generated by Django 5.1.7 on 2025-04-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0005_remove_ieltsreadingsubmission_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltstestsubmit',
            name='score',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='IeltsSpeakingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('additional_information', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_questions', to='ielts.ieltstest')),
            ],
            options={
                'verbose_name_plural': 'Speaking | Tasks',
            },
        ),
    ]
