# Generated by Django 5.1.7 on 2025-04-17 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0006_alter_ieltstestsubmit_score_ieltsspeakingquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltsspeakingquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakings', to='ielts.ieltstest'),
        ),
    ]
