# Generated by Django 5.1.7 on 2025-04-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0007_alter_ieltsspeakingquestion_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltsspeakingquestion',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
