# Generated by Django 5.1.7 on 2025-04-20 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0008_alter_ieltsspeakingquestion_additional_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ieltsspeakingquestion',
            name='test',
        ),
        migrations.AddField(
            model_name='ieltslistening',
            name='part',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3'), (4, 'Part 4')], default=1, verbose_name='Бөлім (Part)'),
        ),
        migrations.AddField(
            model_name='ieltsreading',
            name='passage_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Passage 1'), (2, 'Passage 2'), (3, 'Passage 3')], default=1),
        ),
        migrations.AddField(
            model_name='ieltssubmodule',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Қатар'),
        ),
        migrations.AddField(
            model_name='ieltstest',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='сериялық нөмірі'),
        ),
        migrations.AddField(
            model_name='ieltswriting',
            name='part',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Part 1'), (2, 'Part 2')], default=1, verbose_name='Тапсырма нөмері (Task)'),
        ),
        migrations.AlterField(
            model_name='ieltslistening',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_parts', to='ielts.ieltstest'),
        ),
        migrations.AlterField(
            model_name='ieltsreading',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_passages', to='ielts.ieltstest'),
        ),
        migrations.AlterField(
            model_name='ieltswriting',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to='ielts.ieltstest'),
        ),
        migrations.AlterUniqueTogether(
            name='ieltswriting',
            unique_together={('part', 'test')},
        ),
        migrations.CreateModel(
            name='IeltsSpeakingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.PositiveSmallIntegerField(choices=[(1, 'Part 1 (Interview)'), (2, 'Part 2 (Long Turn / Cue Card)'), (3, 'Part 3 (Discussion)')], default=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_parts', to='ielts.ieltstest')),
            ],
            options={
                'verbose_name_plural': 'Speaking | Parts',
                'unique_together': {('test', 'part')},
            },
        ),
        migrations.AddField(
            model_name='ieltsspeakingquestion',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_questions', to='ielts.ieltsspeakingpart'),
            preserve_default=False,
        ),
    ]
