# Generated by Django 5.1.7 on 2025-04-22 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0009_remove_ieltsspeakingquestion_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltslistening',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listening_parts', to='ielts.ieltstest'),
        ),
    ]
