# Generated by Django 5.1.7 on 2025-04-22 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0010_alter_ieltslistening_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltslistening',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listening_part', to='ielts.ieltstest'),
        ),
    ]
